dspPoolSize: 6
chnlzrHostname: localhost
chnlzrPort: 7070
channelRequestTimeoutMs: 2000
channelQualifyTimeMs: 10000
samplesQueueSize: 10
minControlDataUnitRate: 0.5
minTrafficDataUnitRate: 1.0
controlChannelRetryCount: 3
controlChannelRetryDelayMs: 10000

server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080

kinesis:
  region: us-west-2
  streamName: idk-stream
  accessKeyId: aaabbb111222
  secretKey: cccddd333444
  appName: p25dcodr
  appVersion: v1.0
  payloadsPerRecordMax: 1
  senderPoolSize: 6
  senderQueueSize: 48
  controlDelayMaxMs: 30000
  trafficDelayMaxMs: 30000

cloudWatch:
  accessKeyId: aaabbb111222
  secretKey: cccddd333444
  instanceId: suchInstance
  reportingIntervalMinutes: 1

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
