channelRequestTimeoutMs: 1500
channelQualifyTimeMs: 10000
minControlDataUnitRate: 0.5
minTrafficDataUnitRate: 1.2
controlChannelRetryCount: 3
controlChannelRetryDelayMs: 10000

server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080

chnlzr:
  connectionTimeoutMs: 1250
  idleStateThresholdMs: 2500
  hosts:
    - hostname: localhost
      port: 7070

kinesis:
  region: us-west-2
  streamName: idk-stream
  accessKeyId: aaabbb111222
  secretKey: cccddd333444
  appName: p25dcodr
  appVersion: v1.1
  payloadsPerRecordMax: 1
  senderPoolSize: 12
  senderQueueSize: 48
  controlDelayMaxMs: 30000
  trafficDelayMaxMs: 30000

cloudWatch:
  accessKeyId: aaabbb111222
  secretKey: cccddd333444
  instanceId: suchInstance
  reportingIntervalMinutes: 1

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
